### ISSUE TITLE
TODO items tracking for sparc-x-api

### ISSUE THREAD

**Issue by alchem0x2A** [alchem0x2A/SPARC-X-API#24]
Current TODO lists for the API
- Logistic side
  - [x] Actual v1.0.0 in Github releases
  - [x] Update conda-forge instructions
  - [x] Conda-forge porting of sparc-x-api
  - [x] Renaming to sparc-x-api
  - [ ] Organization-wide wiki mantanance

- Document parser
  Related to #22 
  - [x] Allow parsing manual tex files from subdirs
  - [x] Cyclix and high-T keywords
  - [ ] Tracking ambiguous keywords in original doc 
  - [ ] (TARGET_PRESSURE, NPT_SCALE_VECS, NPT_NH_QMASS, TOL_POISSON)
  
- JSON API (validator)
   - [x] Selecting custom validator (different version)
   - [x] Extra-compatibility for multiline array formats (SPIN, NPT_NPH_QMASS)
   - [ ] Implement rules for keyword compatibility (e.g. CELL / LATVEC_SCALE) for `_check_input_exclusion`
- Stress handling
  Related to #20 
  - [x] Separate standard 3x3 (GPa) stress from low-dimensional stress
  - [x] Store low-dimensional stress as `stress_equiv` field in calc
  - [x] Raise warning / exception when accessing stress info from calc on low-dimensional systems
- BC handling
  Related to #19 
  - [x] SPARC BC to ASE BC mapping
  - [x] Additional fields `sparc_bc` and `twist_angle` in ase atoms conversion
  - [x] ASE <-> SPARC BC objects
  - [x] Detection of zero-length lattice axis
- Cyclix systems
  - [x] Additional keyword compatibility in cyclix
  - [x] Storing cyclix information (should we actually distinguish the radial cell notation from ASE's cartesian one?)
  - [ ] Visualization code (in next release)
- I/O
  Related to #21 
  - [x] Non-standard output compatibility (multiline keywords like SPIN, NPT_NPH_QMASS)
  - [x] Support backward-compatible single file read format (i.e. read_ion, read_static). Use SparcBundle as backend
  - [x] Fix bug in CELL / LATVEC_SCALE rules
  - [x] Parsing additional SCFs in hybrid calculations
  - [ ] Wrap eigen value reader functionality (next release)
- Calculator
  - [x] Support all PBC combinations
  - [x] Calculation caching mechanism (position check for non-periodic system, FFT)
  - [x] Additional alias for different xc names
  - [x] Make sure `convergence` keywords are intuitive 
- Workflow
  - [x] Test script for parsing all official SPARC outputs
  - [x] Test script for reproducing all official SPARC calculation input files
  - [ ] Test script for reproducing quick SPARC calculations
  - [x] Workflow implementation
- Socket implementation
  - [x] Keyword handling for socket calculations
  - [x] Background Popen process implementation
  - [ ] local vs remote socket wrapper in SPARC calc

Additional bugs to be fixed
- [x] Ignore editor temp files, such as .out~, .out# when using indexed images
- [x] Allow parsing incomplete files (static, out)
- [ ] Incomplete geopt and aimd files
- [x] Sorting in socket mode
- [x] Keep / removing old calculation files?
- [x] Socket C-code error handling, allowing clean close
- [x] Test socker server clean closing method
- [x] Default to include_all_files in sparc-ase

**Comment by alchem0x2A** [comment]
Additional bugs to be fixed
- [] Ignore editor temp files, such as .out~, .out# when using indexed images
- [] Allow parsing incomplete files (static, geopt, aimd, out)
- [] Sorting in socket mode

**Comment by alchem0x2A** [comment]
TODO bugs with Socket Interface
- [ ] Use SPARCProtocol in SPARCSocketServer and SPARCSocketClient
- [ ] Make sure sparcbundle sorting information is always present at each writing event
- [ ] Detect change of atoms positions and restart socket
- [ ] implement out_socket from host and port (add unix socket later)
- [ ] where to add additional data to send to socket server?
- [ ] redirect Popen output to the original log file
- [ ] Error return values from socket?
- [ ] Add test function for socket param set

**Comment by alchem0x2A** [comment]
Additional bugs in sparc_bundle
- [x] Sorting information should not be remixing the indices
